sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: NDNqNGsFAAVkqbdb1+FbHxq0HtXf+TBncKpBqxNMgtlMRshqPoO19ak3iFghEINS+hWuviRHz/1ZZ+4ObvFZSl1YCIA0ET3y8VZoFymapt2HVQEUaZuS6CZhm6IAkn97MXmlQgkpGSFpy3HILt0eUyqX4MBzY8N8n6M+xjfpiz8ZqD/tQh+A7SOCteHmhmOaPzzmcqLk9ruRxjYpQ3GuhkqSheOiOdkBYaWrLRoRmIeFGCV966Gjiq9+XwX/n8SiFCW7pTejl6RwACByBKWdqIwsVqT1bv+nL+V1JPlxJtp1DFsiA+OWUGoNVB6xvzicPEilBxzVZpdPg2ydM6FYcOOEXlatNwNQFoMjyD0D25dkLeBN+MHA5XxAuXXpcLrOda0bsI/CMjjRaZtcJuK33O//SawCewQ1FaOOnkLQdYYAh33Y0VFuhQTA4/vn1Ry+dkEJNuKcLRYmpiF7EGl/j76INSmN2+RlAQaye67XJ38FtY/VW4GOl6akvdLvS8sBeZABiWwJoeS0Xsrieu3u8fgTRfq9XUQNZllB/GTDDZRVsuKLnQnLbvduvj152dzVQa+s4SPt1pX+q/puTMnlEABjPb8LZe3E5wWd3JO/qYxvhPJsd/ZIys5M0V+dawejyzWKnAthxhlLRL4Ga/qXa7vb31ivOrk5JNwqKHTWjQs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Fitz-Boodle-Papers_2823
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy